-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


DROP SCHEMA IF EXISTS `MiPapeleriaInt` ;

-- -----------------------------------------------------
-- Schema MiPapeleria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MiPapeleriaInt` DEFAULT CHARACTER SET utf8 ;
USE `MiPapeleriaInt` ;

CREATE TABLE IF NOT EXISTS `MiPapeleriaInt`.`Producto` (
  `ID_Producto` VARCHAR(7) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Localización` VARCHAR(10) NULL,
  `Existencia` TINYINT NOT NULL,
  `Precio` DOUBLE NOT NULL,
  `Marca` varchar(25) not null,
  PRIMARY KEY (`ID_Producto`),
  CONSTRAINT `fkMarca`
    FOREIGN KEY (`Marca`)
    REFERENCES `MiPapeleriaInt`.`Marca` (`Nombre_Marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
  )
ENGINE = InnoDB;


create table if not exists `MiPapeleriaInt`.`Marca`(
  `Nombre_Marca` varchar (25) not null,
  primary key(`Nombre_Marca`))
  ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `MiPapeleriaInt`.`Ventas` (
  `Folio` VARCHAR(7) NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`Folio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MiPapeleria`.`Detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MiPapeleriaInt`.`Detalle_venta` (
  `Productos_ID_Producto` VARCHAR(5) NOT NULL,
  `Ventas_Folio` VARCHAR(7) NOT NULL,
  `Cantidad` TINYINT NOT NULL,
  PRIMARY KEY (`Productos_ID_Producto`, `Ventas_Folio`),
  CONSTRAINT `fk_Productos_has_Ventas_Productos`
    FOREIGN KEY (`Productos_ID_Producto`)
    REFERENCES `MiPapeleriaInt`.`Producto` (`ID_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_has_Ventas_Ventas1`
    FOREIGN KEY (`Ventas_Folio`)
    REFERENCES `MiPapeleriaInt`.`Ventas` (`Folio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Productos_has_Ventas_Ventas1_idx` ON `MiPapeleriaInt`.`Detalle_venta` (`Ventas_Folio` ASC);

CREATE INDEX `fk_Productos_has_Ventas_Productos_idx` ON `MiPapeleriaInt`.`Detalle_venta` (`Productos_ID_Producto` ASC);


-- -----------------------------------------------------
-- Table `MiPapeleria`.`Biografia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MiPapeleriaInt`.`Biografia` (
  `ID_Biografia` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`ID_Biografia`),
  CONSTRAINT `fk_Biografia_Productos1`
    FOREIGN KEY (`ID_Biografia`)
    REFERENCES `MiPapeleriaInt`.`Productos` (`ID_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MiPapeleria`.`Laminas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MiPapeleriaInt`.`Laminas` (
  `ID_Lamina` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`ID_Lamina`),
  CONSTRAINT `fk_Laminas_Productos1`
    FOREIGN KEY (`ID_Lamina`)
    REFERENCES `MiPapeleriaInt`.`Productos` (`ID_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MiPapeleria`.`BioTags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MiPapeleriaInt`.`BioTags` (
  `Tag` VARCHAR(45) NOT NULL,
  `ID_Biografia` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`ID_Biografia`),
  CONSTRAINT `fk_BioTags_Biografia1`
    FOREIGN KEY (`ID_Biografia`)
    REFERENCES `MiPapeleriaInt`.`Biografia` (`ID_Biografia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MiPapeleria`.`LaminaTags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MiPapeleriaInt`.`LaminaTags` (
  `Tag` VARCHAR(45) NOT NULL,
  `ID_Lamina` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`ID_Lamina`),
  CONSTRAINT `fk_LaminaTags_Laminas1`
    FOREIGN KEY (`ID_Lamina`)
    REFERENCES `MiPapeleriaInt`.`Laminas` (`ID_Lamina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- TABLA de ACTIVIADES (OJO, NO TIENE CONEXIÓN CON LAS DEMAS PORQUE NANEJA POR APARTE )
create table Actividades(
Nombre varchar(30), 
Estatus varchar(15), 
FechaEncargo varchar(10), 
FechaCumplimiento varchar(10),
Descripción varchar (80),
PRIMARY KEY (`Nombre`)
)

DROP DATABASE MiPapeleriaInt


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;





